## Numpy Basics ##

In [1]:
import numpy as np
import sys

In [2]:
a = np.array([[1,3,4]],np.int8) #converted into a 2d array
a

array([[1, 3, 4]], dtype=int8)

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
a[0][2]

4

In [5]:
# usually we store like this 

In [6]:
b = range(1000)
print(sys.getsizeof(5) * len(b))

28000


In [7]:
# storing with a numpy object

In [8]:
c = np.arange(1000)
print(c.size*c.itemsize)

4000


In [9]:
# 4000 < 28000 take less storage

In [17]:
a = np.array([[1,2,3],[3,4,5],[23,4443,23]],dtype = np.float64)

In [13]:
a.ndim

2

In [14]:
a.shape

(3, 3)

In [15]:
a.size

9

In [21]:
a.itemsize  #float size

8

In [20]:
type(a)

numpy.ndarray

In [26]:
# creating a zero matrix 
matrix = np.zeros((3,4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
# creating a unit matrix 
matrix = np.ones((3,4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

##  Numpy strings functions  ##

In [31]:
print(np.char.add(["Hello", "Welcome"], [" Friends" , " to Mahesh Guruji"]))

['Hello Friends' 'Welcome to Mahesh Guruji']


In [33]:
print(np.char.center("hello",20, "-"))

-------hello--------


In [39]:
print(np.char.upper("hello WORLd"))

HELLO WORLD


In [45]:
print(np.char.split("Hello How are you"))

['Hello', 'How', 'are', 'you']


In [46]:
print(np.char.strip(['Hello', 'How', 'are', 'you'],"H"))

['ello' 'ow' 'are' 'you']


## Array operations ##

In [52]:
import random
np.random.rand(3,4)

array([[0.33833461, 0.49372375, 0.38513959, 0.1658044 ],
       [0.73212158, 0.21808031, 0.11327078, 0.28548395],
       [0.27610946, 0.17161835, 0.66062681, 0.92899056]])

In [53]:
np.random.randint(7,size = (3,3))

array([[5, 4, 3],
       [3, 5, 1],
       [4, 5, 3]])

In [54]:
np.random.randint(-4,5,size = (3,3))

array([[ 2, -4, -3],
       [-1,  4,  4],
       [-4, -3, -1]])

In [60]:
np.random.randint(10,101)

33

In [62]:
#Initalize and append the random numbers 
RandomNumber = []
for i in range(50):
    RandomNumber.append(np.random.randint(low = 0 , high = 50))
print(RandomNumber)

[15, 27, 15, 30, 44, 19, 34, 49, 8, 3, 20, 4, 6, 2, 29, 20, 22, 5, 12, 12, 6, 34, 42, 32, 30, 2, 7, 31, 40, 33, 30, 36, 22, 18, 38, 25, 35, 16, 43, 8, 26, 7, 40, 11, 19, 37, 39, 31, 20, 34]


In [65]:
np.random.seed(3)
print(np.random.randint(100,500)) #This is save the state of randomness and returns the same value every time you run it

462


In [69]:
np.random.rand(2,3,4)

array([[[0.75766525, 0.81757073, 0.25758529, 0.89306511],
        [0.71842202, 0.0206145 , 0.14271733, 0.32530618],
        [0.8089292 , 0.39899095, 0.42470161, 0.41371868]],

       [[0.7871385 , 0.71356575, 0.02311757, 0.31576725],
        [0.56277009, 0.74815744, 0.60962367, 0.20335453],
        [0.65363085, 0.66268627, 0.87107205, 0.81122776]]])

In [71]:
np.empty((2,3))

array([[6.23042070e-307, 1.33512376e-306, 1.11261230e-306],
       [7.56577399e-307, 9.34600963e-307, 1.05699581e-307]])

In [72]:
np.full(5,1)

array([1, 1, 1, 1, 1])

In [73]:
np.full(10,100,dtype = "f8")

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [74]:
#accessing digonal elements 
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
np.diag([3,2])

array([[3, 0],
       [0, 2]])